//apple
TreeRegistry.deriveTreeAsClass("Harvestcraft_middleFruitTree",{
	name:"apple",
	sapling:{
		block:BlockID.appleTreeSapling,
		item:ItemID.appleSapling
	},
	fruit:{
		block:BlockID.appleBlock,
		item:260
	}
});

//apricot
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"apricot",
	sapling:{
		block:BlockID.apricotTreeSapling,
		item:ItemID.apricotSapling
	},
	fruit:{
		block:BlockID.apricot,
		item:ItemID.apricot
	}
});

//cherry
TreeRegistry.deriveTreeAsClass("Harvestcraft_middleFruitTree",{
	name:"cherry",
	sapling:{
		block:BlockID.cherryTreeSapling,
		item:ItemID.cherrySapling
	},
	fruit:{
		block:BlockID.cherry,
		item:ItemID.cherry
	}
});

//avocado
TreeRegistry.deriveTreeAsClass("Harvestcraft_middleFruitTree",{
	name:"avocado",
	sapling:{
		block:BlockID.avocadoTreeSapling,
		item:ItemID.avocadoSapling
	},
	fruit:{
		block:BlockID.avocado,
		item:ItemID.avocado
	}
});

//banana
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"banana",
	sapling:{
		block:BlockID.bananaTreeSapling,
		item:ItemID.bananaSapling
	},
	fruit:{
		block:BlockID.banana,
		item:ItemID.banana
	}
});

//date
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"date",
	sapling:{
		block:BlockID.dateTreeSapling,
		item:ItemID.dateSapling
	},
	fruit:{
		block:BlockID.date,
		item:ItemID.date
	}
});

//dragonfruit
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"dragonfruit",
	sapling:{
		block:BlockID.dragonfruitTreeSapling,
		item:ItemID.dragonfruitSapling
	},
	fruit:{
		block:BlockID.dragonfruit,
		item:ItemID.dragonfruit
	}
});

//fig
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"fig",
	sapling:{
		block:BlockID.figTreeSapling,
		item:ItemID.figSapling
	},
	fruit:{
		block:BlockID.fig,
		item:ItemID.fig
	}
});

//grapefruit
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"grapefruit",
	sapling:{
		block:BlockID.grapefruitTreeSapling,
		item:ItemID.grapefruitSapling
	},
	fruit:{
		block:BlockID.grapefruit,
		item:ItemID.grapefruit
	}
});

//gooseberry
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"gooseberry",
	sapling:{
		block:BlockID.gooseberryTreeSapling,
		item:ItemID.gooseberrySapling
	},
	fruit:{
		block:BlockID.gooseberry,
		item:ItemID.gooseberry
	}
});

//lemon
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"lemon",
	sapling:{
		block:BlockID.lemonTreeSapling,
		item:ItemID.lemonSapling
	},
	fruit:{
		block:BlockID.lemon,
		item:ItemID.lemon
	}
});

//lime
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"lime",
	sapling:{
		block:BlockID.limeTreeSapling,
		item:ItemID.limeSapling
	},
	fruit:{
		block:BlockID.lime,
		item:ItemID.lime
	}
});

//mango
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"mango",
	sapling:{
		block:BlockID.mangoTreeSapling,
		item:ItemID.mangoSapling
	},
	fruit:{
		block:BlockID.mango,
		item:ItemID.mango
	}
});

//olive
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"olive",
	sapling:{
		block:BlockID.oliveTreeSapling,
		item:ItemID.oliveSapling
	},
	fruit:{
		block:BlockID.olive,
		item:ItemID.olive
	}
});

//orange
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"orange",
	sapling:{
		block:BlockID.orangeTreeSapling,
		item:ItemID.orangeSapling
	},
	fruit:{
		block:BlockID.orange,
		item:ItemID.orange
	}
});

//papaya
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"papaya",
	sapling:{
		block:BlockID.papayaTreeSapling,
		item:ItemID.papayaSapling
	},
	fruit:{
		block:BlockID.papaya,
		item:ItemID.papaya
	}
});

//peach
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"peach",
	sapling:{
		block:BlockID.peachTreeSapling,
		item:ItemID.peachSapling
	},
	fruit:{
		block:BlockID.peach,
		item:ItemID.peach
	}
});

//pear
TreeRegistry.deriveTreeAsClass("Harvestcraft_taigaFruitTree",{
	name:"pear",
	sapling:{
		block:BlockID.pearTreeSapling,
		item:ItemID.pearSapling
	},
	fruit:{
		block:BlockID.pear,
		item:ItemID.pear
	}
});

//persimmon
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"persimmon",
	sapling:{
		block:BlockID.persimmonTreeSapling,
		item:ItemID.persimmonSapling
	},
	fruit:{
		block:BlockID.persimmon,
		item:ItemID.persimmon
	}
});

//plum
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"plum",
	sapling:{
		block:BlockID.plumTreeSapling,
		item:ItemID.plumSapling
	},
	fruit:{
		block:BlockID.plum,
		item:ItemID.plum
	}
});

//pomegranate
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"pomegranate",
	sapling:{
		block:BlockID.pomegranateTreeSapling,
		item:ItemID.pomegranateSapling
	},
	fruit:{
		block:BlockID.pomegranate,
		item:ItemID.pomegranate
	}
});

//starfruit
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"starfruit",
	sapling:{
		block:BlockID.starfruitTreeSapling,
		item:ItemID.starfruitSapling
	},
	fruit:{
		block:BlockID.starfruit,
		item:ItemID.starfruit
	}
});

//almond
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"almond",
	sapling:{
		block:BlockID.almondTreeSapling,
		item:ItemID.almondSapling
	},
	fruit:{
		block:BlockID.almond,
		item:ItemID.almond
	}
});

//peppercorn
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"peppercorn",
	sapling:{
		block:BlockID.peppercornTreeSapling,
		item:ItemID.peppercornSapling
	},
	fruit:{
		block:BlockID.peppercornfruit,
		item:ItemID.peppercorn
	}
});

//cashew
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"cashew",
	sapling:{
		block:BlockID.cashewTreeSapling,
		item:ItemID.cashewSapling
	},
	fruit:{
		block:BlockID.cashew,
		item:ItemID.cashew
	}
});

//coconut
TreeRegistry.deriveTreeAsClass("Harvestcraft_jungleFruitTree",{
	name:"coconut",
	sapling:{
		block:BlockID.coconutTreeSapling,
		item:ItemID.coconutSapling
	},
	fruit:{
		block:BlockID.coconut,
		item:ItemID.coconut
	}
});